### ISSUE TITLE
Размер текста

### ISSUE THREAD

**Issue by druid82** [dejurin/php-google-translate-for-free#1]
Здравствуйте. Спасибо за такой хороший скрипт. Всё работает. Но есть один нюанс.
Я перевожу русский тест на английский. Тексты примерно все одного размера 3-3,5 тысячи символов.
Выдает ошибку о превышении допустимого предела в 5к символов. При увеличении ограничения в скрипте до 10 тысяч символов. Всё равно выдаёт эту же ошибку. А вот при увеличении до 15 000 - проходит и срабатывает. Как считает символы? Могу выслать пример текста.

**Comment by dejurin** [comment]
Высылайте, протестируем. Но мне кажется, что проблема кроется где-то в самом API google, так как в скрипте нет никаких ограничений.
