### ISSUE TITLE
Can I be denied access or a captcha?

### ISSUE THREAD

**Issue by borma425** [dejurin/php-google-translate-for-free#7]
I really liked the project
I was wondering is it guaranteed not to stop?
Like blocking google, captcha check, or…
Because I found it doesn't use an official api
![image](https://user-images.githubusercontent.com/42983220/138801034-7a57b541-5b0f-45e8-beae-df5f1b2c8211.png)

**Comment by dejurin** [comment]
I can't guarantee, it all depends on google. I can tell you that this method has been working for 5 years.
